### ISSUE TITLE
Unknown Property – yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by gquimper** [DeuxHuitHuit/craft-cloudflare-stream#6]
Hi, I would really like to use your plugin on a project, but it seems the current version (1.4) is generating an error when I try to edit an entry with a stream field. 

Craft version: 4.5.6.1
Plugin version: 1.4
PHP version: 8.2

Here's the complete stackstrace of the error I'm getting:
yii\base\UnknownPropertyException: Getting unknown property: craft\elements\Entry::kind in /Users/guillaumequimper/www-root/tvc9/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/base/Element.php(2186): yii\base\Component->__get('kind')
#1 /Users/guillaumequimper/www-root/tvc9/vendor/deuxhuithuit/craft-cloudflare-stream/src/fields/CloudflareVideoStreamField.php(44): craft\base\Element->__get('kind')
#2 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(273): deuxhuithuit\cfstream\fields\CloudflareVideoStreamField->getInputHtml(NULL, Object(craft\elements\Entry))
#3 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(235): craft\fieldlayoutelements\CustomField->inputHtml(Object(craft\elements\Entry), false)
#4 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(222): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Entry), false)
#5 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/web/View.php(1628): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#6 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(221): craft\web\View->namespaceInputs(Object(Closure), 'fields')
#7 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/models/FieldLayout.php(738): craft\fieldlayoutelements\CustomField->formHtml(Object(craft\elements\Entry), false)
#8 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/web/View.php(1622): craft\models\FieldLayout->craft\models\{closure}()
#9 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/models/FieldLayout.php(737): craft\web\View->namespaceInputs(Object(Closure), NULL)
#10 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/controllers/ElementsController.php(802): craft\models\FieldLayout->createForm(Object(craft\elements\Entry), false, Array)
#11 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/controllers/ElementsController.php(406): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Entry), false, true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#12 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#13 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(121): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#14 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(49): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#15 /Users/guillaumequimper/www-root/tvc9/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#16 /Users/guillaumequimper/www-root/tvc9/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#17 /Users/guillaumequimper/www-root/tvc9/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#18 /Users/guillaumequimper/www-root/tvc9/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#19 /Users/guillaumequimper/www-root/tvc9/web/index.php(12): yii\base\Application->run()
#20 {main}

**Comment by nitriques** [comment]
Hi ! Sorry for the late response, but this should now be fixed !

Thanks!
