### ISSUE TITLE
Uploads not possible with current version and R2 filesystem

### ISSUE THREAD

**Issue by fthues** [DeuxHuitHuit/craft-cloudflare-stream#7]
Unfortunately PR #5 seems to have broken the plugin for us. 
For one, auto-upload isn't working anymore, we're seeing this error after every attempted asset upload.

```
Getting unknown property: jrrdnx\cloudflarer2\Fs::rootPath
```

Caused by this: https://github.com/DeuxHuitHuit/craft-cloudflare-stream/blob/94804bed7ba196bcd91cf8c3decb6271535b40d2/src/Plugin.php#L92

We're using a Cloudflare R2 filesystem.

We disabled auto-uploading, but that just gave us this (related) error, a non-existing variable `$asset` is being referenced:

```
yii\base\ErrorException: Undefined variable $asset in /var/www/html/vendor/deuxhuithuit/craft-cloudflare-stream/src/controllers/UploadController.php:49
```

https://github.com/DeuxHuitHuit/craft-cloudflare-stream/blob/94804bed7ba196bcd91cf8c3decb6271535b40d2/src/controllers/UploadController.php#L49

**Comment by nitriques** [comment]
Hi ! sorry for the late response, but this should be fixed as of 1.4.2

If you still have errors, please reopen the issue !

Thanks!
